// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Info struct {
	Text       string  `json:"text"`
	Job        string  `json:"job"`
	Desc       string  `json:"desc"`
	Experience string  `json:"experience"`
	Telegram   string  `json:"telegram"`
	Github     *string `json:"github"`
}

type NewInfo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}
