// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ServiceErrorInterface interface {
	IsServiceErrorInterface()
}

type UserOutput interface {
	IsUserOutput()
}

type Contacts struct {
	Telegram string `json:"telegram"`
	Github   string `json:"github"`
}

type DeleteWork struct {
	ID int `json:"id"`
}

type GetInfo struct {
	Name       string    `json:"name"`
	Job        string    `json:"job"`
	Desc       string    `json:"desc"`
	Experience string    `json:"experience"`
	Contacts   *Contacts `json:"contacts"`
}

type GetWork struct {
	ID          int     `json:"id"`
	Name        string  `json:"name"`
	Tags        string  `json:"tags"`
	Description string  `json:"description"`
	Github      *string `json:"github"`
	Demo        string  `json:"demo"`
	Figma       string  `json:"figma"`
}

type NotFoundError struct {
	Message string `json:"message"`
}

func (NotFoundError) IsUserOutput() {}

type UpdateInfo struct {
	Name       string `json:"name"`
	Job        string `json:"job"`
	Desc       string `json:"desc"`
	Experience string `json:"experience"`
	Telegram   string `json:"telegram"`
	Github     string `json:"github"`
}

type UpdateWork struct {
	ID          int     `json:"id"`
	Name        string  `json:"name"`
	Tags        string  `json:"tags"`
	Description string  `json:"description"`
	Github      *string `json:"github"`
	Demo        string  `json:"demo"`
	Figma       string  `json:"figma"`
}

type User struct {
	ID       int    `json:"id"`
	Login    string `json:"login"`
	Password string `json:"password"`
}

func (User) IsUserOutput() {}

type UserInput struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}
