// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Info struct {
	Name       string  `json:"name"`
	Job        string  `json:"job"`
	Desc       string  `json:"desc"`
	Experience string  `json:"experience"`
	Telegram   string  `json:"telegram"`
	Github     *string `json:"github"`
}

type Work struct {
	ID          int     `json:"id"`
	Name        string  `json:"name"`
	Tags        string  `json:"tags"`
	Description string  `json:"description"`
	Github      *string `json:"github"`
	Demo        string  `json:"demo"`
	Figma       string  `json:"figma"`
}

type EditInfo struct {
	Name       string  `json:"name"`
	Job        string  `json:"job"`
	Desc       string  `json:"desc"`
	Experience string  `json:"experience"`
	Telegram   string  `json:"telegram"`
	Github     *string `json:"github"`
}
